#!/usr/bin/env bash
# This script displays bad luck on 4th iteration, good luck on 8th, and Best School otherwise
i=1
while [ $i -le 10 ]
do
  if [ $i -eq 4 ]
  then
    echo "bad luck"
  elif [ $i -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
